name: Run Data Migration Script

on: 
  push:
    branches:
      - main

jobs:
  run-migrations:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: production
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup pnpm
      # Use the action to install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest 
        run_install: false # Defer installation to the next step

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Specify 'pnpm' for automatic caching
        cache: 'pnpm' 

    - name: Install dependencies
      # The `actions/setup-node` with `cache: 'pnpm'` will automatically
      # restore the cache and the next `pnpm install` will use it.
      run: pnpm install --frozen-lockfile

    - name: Run migrations
      run: pnpm run db:setup
